### ISSUE TITLE
【BUG】使用快捷键删除标注框无效

### ISSUE THREAD

**Issue by Gypsophila123** [opendatalab/labelU#106]
标注工具：拉框
快捷键提示按 Del 或 Backspace 可以删除标注框。
但在实际情况中，使用快捷键删除标注框后，右侧标记栏中标注框依旧存在。并且虽然在图像中标注框不再显示，但如果重新打开该图片标注框又重新显示。

**Comment by gary-Shen** [comment]
好的，谢谢反馈。我们会尽快修复。
