### ISSUE TITLE
【BUG】预标注文件超过100后不加载

### ISSUE THREAD

**Issue by Gypsophila123** [opendatalab/labelU#107]
前100个预标注文件都成功的在图像上显示了，从第101个图像开始预标注文件不能成功显示

**Comment by Gypsophila123** [comment]
补充一下，在列表上预标注文件是能看到的，但进标注页面看不见预标注框
![image](https://github.com/opendatalab/labelU/assets/63332682/df200d8f-6619-4da6-a21e-3abc3fcff4e0)

**Comment by gary-Shen** [comment]
OK，我们复现看看。

**Comment by sunfan1997** [comment]
解决了吗，我也遇到了。
在旧项目，上传第101个时，预标注不显示。
新建项目，一口气上传200个，100个以后的预标注也不显示。

**Comment by gary-Shen** [comment]
> 解决了吗，我也遇到了。
> 
> 在旧项目，上传第101个时，预标注不显示。
> 
> 新建项目，一口气上传200个，100个以后的预标注也不显示。

还没更新。不过应该今明两天会发一个版本。

**Comment by gary-Shen** [comment]
@Gypsophila123 @sunfan1997 
两位可以安装 alpha 版本先试试看：`pip install -i https://test.pypi.org/simple/ labelu==1.0.6a1`。

目前在优化预标注的查询逻辑。

**Comment by sunfan1997** [comment]
> @Gypsophila123 @sunfan1997 两位可以安装 alpha 版本先试试看：`pip install -i https://test.pypi.org/simple/ labelu==1.0.6a1`。
> 
> 目前在优化预标注的查询逻辑，正式版本会晚点更新。

这个版本可行，100以后的预标注能显示，安装命令：pip install --extra-index-url https://test.pypi.org/simple/ labelu==1.0.6a1
