### ISSUE TITLE
视频分类编码格式不支持

### ISSUE THREAD

**Issue by sfeng-m** [opendatalab/labelU#111]
上传的视频格式为H.264的mp4视频文件（导入文件时要求的格式），但标注的时候显示“暂不支持此编码的视频数据”。请问这是什么原因？

**Comment by gary-Shen** [comment]
<img width="582" alt="image" src="https://github.com/opendatalab/labelU/assets/10260860/c424217f-6e37-4cf8-9f54-6e9b332bf4ea">


另外可以用 `ffmpeg` 来查看编码格式，先安装 `ffmpeg`，然后运行：


```bash
ffprobe -v error -show_format -show_streams /Users/gary/Downloads/video-segment.mp4
```

output:

```
[STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=High
codec_type=video
codec_tag_string=avc1
codec_tag=0x31637661
width=1920
height=1080
coded_width=1920
coded_height=1080
closed_captions=0
film_grain=0
has_b_frames=2
sample_aspect_ratio=1:1
display_aspect_ratio=16:9
pix_fmt=yuv420p
level=40
color_range=tv
color_space=bt709
color_transfer=bt709
color_primaries=bt709
chroma_location=left
field_order=progressive
refs=1
is_avc=true
nal_length_size=4
id=0x1
r_frame_rate=30/1
avg_frame_rate=30/1
time_base=1/15360
start_pts=0
start_time=0.000000
duration_ts=270848
duration=17.633333
bit_rate=1948050
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=529
nb_read_frames=N/A
nb_read_packets=N/A
extradata_size=51
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
TAG:language=und
TAG:handler_name=ETI ISO Video Media Handler
TAG:vendor_id=[0][0][0][0]
TAG:encoder=Lavc60.30.101 libx264
[/STREAM]
[FORMAT]
filename=/Users/gary/Downloads/video-segment.mp4
nb_streams=1
nb_programs=0
nb_stream_groups=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0.000000
duration=17.633333
size=4301142
bit_rate=1951368
probe_score=100
TAG:major_brand=isom
TAG:minor_version=512
TAG:compatible_brands=isomiso2avc1mp41
TAG:encoder=Lavf60.15.100
[/FORMAT]
```

**Comment by sfeng-m** [comment]
这是我用ffmpeg 查看编码格式的结果，显示为h264，但还是显示暂不支持此编码的视频数据。

ffprobe -v error -show_format -show_streams 1.mp4
[STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=High
codec_type=video
codec_time_base=1/10
codec_tag_string=avc1
codec_tag=0x31637661
width=154
height=140
coded_width=160
coded_height=144
has_b_frames=2
sample_aspect_ratio=N/A
display_aspect_ratio=N/A
pix_fmt=yuv420p
level=10
color_range=unknown
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
field_order=unknown
timecode=N/A
refs=1
is_avc=true
nal_length_size=4
id=N/A
r_frame_rate=5/1
avg_frame_rate=5/1
time_base=1/10240
start_pts=0
start_time=0.000000
duration_ts=34816
duration=3.400000
bit_rate=59663
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=17
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
TAG:language=und
TAG:handler_name=VideoHandler
[/STREAM]
[FORMAT]
filename=1_12575_12650_622#552#776#692.mp4
nb_streams=1
nb_programs=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0.000000
duration=3.400000
size=26380
bit_rate=62070
probe_score=100
TAG:major_brand=isom
TAG:minor_version=512
TAG:compatible_brands=isomiso2avc1mp41
TAG:encoder=Lavf58.29.100
[/FORMAT]

**Comment by gary-Shen** [comment]
方便把视频上传上来吗？

**Comment by sfeng-m** [comment]
https://github.com/opendatalab/labelU/assets/54133656/e5456adb-220b-4e2b-929d-200bf0353e84

**Comment by gary-Shen** [comment]
> 1_123057_123132_613.779.858.1002.mp4

看起来好像打不开。可以用浏览器打开你本地的这个视频看看能不能播放，如果不能，说明在labelu里也无法播放。

**Comment by sfeng-m** [comment]
嗯嗯，用mac的QuickTime Player无法打开，用其他播放器可以(如Elmedia Player)，这个视频可以怎么改编码格式使得labelu可以支持播放吗，还是说是原视频的问题，无论怎么改格式都是无法支持的？

**Comment by gary-Shen** [comment]
可以尝试用 ffmpeg 来再转一次：
```bash
ffmpeg -i ./video-segment.mp4 -c:v libx264 -profile:v high -level:v 4.0 -pix_fmt yuv420p -c:a aac -b:a 128k -movflags +faststart output.mp4
```

**Comment by sfeng-m** [comment]
我原来是用用了这个命令可以

**Comment by sfeng-m** [comment]
我原来是用moviepy保存视频的时候指定的h264格式，用了ffmpeg再转一次可以了，非常感谢~
ps: 我的视频的宽度和高度不满足要求，所以转的时候需要做一点调整，给有需要的小伙伴参考：
ffmpeg -i input.mp4 -vf "scale='if(gt(a,16/9),-2,2*trunc(oh*a/2))':'if(gt(a,16/9),2*trunc(ow/(a/2)), -2)',pad=ceil(iw/2)*2:ceil(ih/2)*2" -c:v libx264 -profile:v high -level:v 4.0 -pix_fmt yuv420p -c:a aac -b:a 128k -movflags +faststart output.mp4
