### ISSUE TITLE
如何将使用labelu标注好的导出结果重新导入回去继续修改查看

### ISSUE THREAD

**Issue by LongHZ140516** [opendatalab/labelU#113]
你好，非常感谢你们的工作。但目前我遇到一个问题：我使用labelu标注了视频，将标注结果的json文件导出后，似乎不能直接将其导入回labelu查看标注情况。我尝试将导出的json文件按照预标注的jsonl格式整理，但依然无法导入，显示解析失败。下面是整理的jsonl信息。我想将标注的结果重新导入回去但总是失败。
`{
    "sample_name": "OpenAI_Sora.mp4",
    "config": {
      "videoSegmentTool": [
        {
          "color": "#ff6600",
          "key": "标签-1",
          "value": "label-1"
        }
      ],
      "videoFrameTool": [
        {
          "color": "#0040ff",
          "key": "标签-1",
          "value": "label-1"
        }
      ]
    },
    "annotations": {
      "videoSegmentTool": {
        "toolName": "videoSegmentTool",
        "result": [
          {
            "id": "zhnea4c0sy",
            "start": 10.580564817268963,
            "end": 11.382882,
            "order": 1,
            "label": "issue",
            "attributes": {
              "illustrate": [
                "wwwwwww"
              ]
            }
          }
        ]
      },
      "videoFrameTool": {
        "toolName": "videoFrameTool",
        "result": [
          {
            "id": "f3a13bove67",
            "time": 4.7637612704017,
            "label": "case",
            "order": 2,
            "attributes": {
              "illustrate": "xxxxxxxx"
            }
          }
        ]
      },
      "textTool": {
        "toolName": "textTool",
        "result": [
          {
            "id": "xjyk4e0bqid",
            "type": "text",
            "value": {
              "overall_issue": "xxxxx，xxxxxx"
            }
          }
        ]
      }
    }
  }`

**Comment by gary-Shen** [comment]
目前是不支持的。目前可以手动转换为预标注 jsonl 文件的格式，或者自行写脚本处理哈。

**Comment by LongHZ140516** [comment]
好的，非常感谢。我后续会再尝试下转换为jsonl文件格式，我检查下我转换是否存在问题。

**Comment by gary-Shen** [comment]
可以把这个几个图片的标注放在一个jsonl里面，一个图片一行。

**Comment by YunfengLiu** [comment]
好的，谢谢。😊

**Comment by LongHZ140516** [comment]
你好 @YunfengLiu 
我自己写了一段code来批量将json转为jsonl文件，或许你可以尝试一下，我在使用的时候似乎没有问题。你可以根据自己的标注工具信息对inf部分进行修改。希望能帮到你。
```
import os
import json
import argparse

class video_json():
    def __init__(self, data):
        self.sample_name = data['fileName']
        self.result = data['result']
        self.judge_annotation()

    def judge_annotation(self):
        result_json = json.loads(self.result)
        if 'annotations' in result_json:
            self.annotations = result_json['annotations']
        else:
            self.annotations = {}
        
    def judge_tool_used(self):
        self.tool_inf = {}
        for annotation in self.annotations:
            if annotation['toolName'] == "rectTool":
                self.tool_inf.update({'rectTool': annotation})

            elif annotation['toolName'] == "textTool":
                self.tool_inf.update({'textTool': annotation})
            # self.tool_inf.update({'textTool': annotation})

    def export_inf(self):
        self.judge_tool_used()
        json_inf = {
            "sample_name": self.sample_name,
            "config": {
                "rectTool": [
                    {
                        "color": "#ff6600",
                        "key": "问题",
                        "value": "issue"
                    }
                ]
            },
            "annotations": self.tool_inf
        }
        return json_inf

  if __name__ == "__main__":
      parser = argparse.ArgumentParser()
      parser.add_argument("--data_path", help="path to json file(.json)", default=r"D:\FakeBench\fake_image\FakeImage_dataset\LabelU_fix_json")
      parser.add_argument("--output_path", help="path to output jsonl file (.jsonl)", default="")

    args = parser.parse_args()

    files = os.listdir(args.data_path)
    json_files = [file for file in files if file.endswith('.json')]
    
    for file in json_files:
        print("processing file: ", file)
        output_file = os.path.join(args.output_path, file.replace('.json', '.jsonl'))
        with open(os.path.join(args.data_path, file), 'r', encoding='utf-8') as json_file:
            data = json.load(json_file)

        with open(output_file, 'w+', encoding='utf-8') as jsonl_file:
            for idx, case in enumerate(data):
                inf = video_json(case).export_inf()
                if idx != len(data) - 1:
                    jsonl_file.write(json.dumps(inf, ensure_ascii=False) + '\n')
                else:
                    jsonl_file.write(json.dumps(inf, ensure_ascii=False))
    
    print("-----json to jsonl done-----")
```

**Comment by YunfengLiu** [comment]
> 你好 @YunfengLiu 我自己写了一段code来批量将json转为jsonl文件，或许你可以尝试一下，我在使用的时候似乎没有问题。你可以根据自己的标注工具信息对inf部分进行修改。希望能帮到你。
> 
> ```
> import os
> import json
> import argparse
> 
> class video_json():
>     def __init__(self, data):
>         self.sample_name = data['fileName']
>         self.result = data['result']
>         self.judge_annotation()
> 
>     def judge_annotation(self):
>         result_json = json.loads(self.result)
>         if 'annotations' in result_json:
>             self.annotations = result_json['annotations']
>         else:
>             self.annotations = {}
>         
>     def judge_tool_used(self):
>         self.tool_inf = {}
>         for annotation in self.annotations:
>             if annotation['toolName'] == "rectTool":
>                 self.tool_inf.update({'rectTool': annotation})
> 
>             elif annotation['toolName'] == "textTool":
>                 self.tool_inf.update({'textTool': annotation})
>             # self.tool_inf.update({'textTool': annotation})
> 
>     def export_inf(self):
>         self.judge_tool_used()
>         json_inf = {
>             "sample_name": self.sample_name,
>             "config": {
>                 "rectTool": [
>                     {
>                         "color": "#ff6600",
>                         "key": "问题",
>                         "value": "issue"
>                     }
>                 ]
>             },
>             "annotations": self.tool_inf
>         }
>         return json_inf
> 
>   if __name__ == "__main__":
>       parser = argparse.ArgumentParser()
>       parser.add_argument("--data_path", help="path to json file(.json)", default=r"")
>       parser.add_argument("--output_path", help="path to output jsonl file (.jsonl)", default="")
> 
>     args = parser.parse_args()
> 
>     files = os.listdir(args.data_path)
>     json_files = [file for file in files if file.endswith('.json')]
>     
>     for file in json_files:
>         print("processing file: ", file)
>         output_file = os.path.join(args.output_path, file.replace('.json', '.jsonl'))
>         with open(os.path.join(args.data_path, file), 'r', encoding='utf-8') as json_file:
>             data = json.load(json_file)
> 
>         with open(output_file, 'w+', encoding='utf-8') as jsonl_file:
>             for idx, case in enumerate(data):
>                 inf = video_json(case).export_inf()
>                 if idx != len(data) - 1:
>                     jsonl_file.write(json.dumps(inf, ensure_ascii=False) + '\n')
>                 else:
>                     jsonl_file.write(json.dumps(inf, ensure_ascii=False))
>     
>     print("-----json to jsonl done-----")
> ```

好的，非常感谢你的帮助。
