### ISSUE TITLE
标注文件json导出后result部分全是转义字符

### ISSUE THREAD

**Issue by Yongsun1998** [opendatalab/labelU#116]
![image](https://github.com/user-attachments/assets/0b2295e7-c5ac-430e-a321-37cd3751b20e)

**Comment by gary-Shen** [comment]
result是json字符串，可以正常解析的。

**Comment by Yongsun1998** [comment]
感谢您的回复，这个软件很好用。但是我测试了一下，导出来的原始json文件是这样的：


[{"id":1,"result":"{\"annotations\": [{\"toolName\": \"videoSegmentTool\", \"result\": [{\"id\": \"bgwbyijrea\", \"start\": 2.428258, \"end\": 11.607077, \"order\": 1, \"label\": \"day2\", \"attributes\": {\"stage_quality\": [\"good\"], \"stage_report\": \"细胞数目：4\\n均匀度：均匀\\n碎片程度：<10%\"}}, {\"id\": \"36sb2r5drto\", \"start\": 11.655642, \"end\": 20.883027, \"order\": 2, \"label\": \"day3\", \"attributes\": {\"stage_quality\": [\"fair\"], \"stage_report\": \"细胞数目：7\\n均匀度：具备阶段特异性\\n碎片程度：<10%\"}}, {\"id\": \"lghbp13f8ni\", \"start\": 30.110411, \"end\": 39.434925, \"order\": 3, \"label\": \"day5\", \"attributes\": {\"stage_quality\": [\"fair\"], \"stage_report\": \"内细胞团：细胞数目尚可，但细胞间连接较松散\\n外滋养层细胞：细胞数目较多，排列紧密，大小均匀\"}}, {\"id\": \"8si7l6n2jxr\", \"start\": 5.828981559668153, \"end\": 9.763544112444157, \"order\": 4, \"label\": \"one-cell-stage\"}, {\"id\": \"o3oq3hb0p\", \"start\": 4.902394, \"end\": 8.795917, \"order\": 5, \"label\": \"two-cell-stage\"}, {\"id\": \"fgdcnnber47\", \"start\": 9.855913, \"end\": 13.692765, \"order\": 6, \"label\": \"four-cell-stage\"}, {\"id\": \"w4r0a5fudwp\", \"start\": 10.1521428830887, \"end\": 13.681623, \"order\": 7, \"label\": \"eight-cell-stage\"}]}, {\"toolName\": \"textTool\", \"result\": [{\"id\": \"g59tyc96kq9\", \"value\": {\"overall report\": \"本视频记录的体外受精胚胎发育过程，初期卵裂速度适中，细胞形态尚均匀，但随后进入囊胚期时，扩张程度一般，内细胞团与滋养层细胞比例适中但略显不均，伴有一定量碎片。总体而言，胚胎发育质量评估为一般。\"}}]}, {\"toolName\": \"tagTool\", \"result\": [{\"id\": \"ln4q367vmii\", \"value\": {\"overall_quality\": [\"fair\"]}}]}]}","url":"/api/v1/tasks/attachment/upload/1/13c4b619-8月17日.mp4","fileName":"8月17日.mp4"}]



我使用网上的json在线解析是只能把result部分解析成一个大的字符串。您的意思是使用python解析就正常了吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月17日(星期六) 下午2:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [opendatalab/labelU] 标注文件json导出后result部分全是转义字符 (Issue #116)














 
result是json字符串，可以正常解析的。

**Comment by Yongsun1998** [comment]
是我无知，网页上解析确实解析不出来，但是使用python解析就ok。
