### ISSUE TITLE
说开源，结果页面不给开源，无法修改二开

### ISSUE THREAD

**Issue by zhangzhiliang0107** [opendatalab/labelU#121]
![微信图片_20240828174050](https://github.com/user-attachments/assets/5edad8a0-546b-4753-bcc2-15dba10bf89a)
我想可以修改页面，独立部署

**Comment by gary-Shen** [comment]
前端源码在另一个仓库：https://github.com/opendatalab/labelU-Kit/blob/main/CONTRIBUTION_GUIDE.md
