### ISSUE TITLE
启动服务器后localhost无法连接

### ISSUE THREAD

**Issue by hyzgogogo** [opendatalab/labelU#122]
需要在电脑上打开什么服务吗？
![image](https://github.com/user-attachments/assets/fdd2ef73-aee8-46ee-944b-6c97d3292a0a)
![image](https://github.com/user-attachments/assets/af2b776f-3ffd-46cd-90ee-5fec44f9b13f)

**Comment by gary-Shen** [comment]
什么浏览器打开的？换一个浏览器看看？

**Comment by hyzgogogo** [comment]
![Uploading image.png…]()
