### ISSUE TITLE
数据总览和开始标注存在bug

### ISSUE THREAD

**Issue by flinzhao** [opendatalab/labelU#68]
![20231206092037](https://github.com/opendatalab/labelU/assets/103496889/d201ace4-8b97-4191-965d-0118614f1acc)
① 总共上传133张图像，但数据ID却大于133。
![image](https://github.com/opendatalab/labelU/assets/103496889/b1267880-a72c-47fc-acf1-b6722aaa9fe8)
② 在多边形标注中，左侧的图像列表只显示40张图像，而我需要标注133张图像

**Comment by gary-Shen** [comment]
谢谢反馈🫡，可否提供版本号呢？
浏览器控制台：输入__backend后回车，可以看到版本号。

**Comment by flinzhao** [comment]
![image](https://github.com/opendatalab/labelU/assets/103496889/ce0ced30-6277-45b2-8ba7-ac19f258dc35)
![image](https://github.com/opendatalab/labelU/assets/103496889/059c137d-a2eb-4396-a620-2ac45f040803)

**Comment by gary-Shen** [comment]
> ![image](https://private-user-images.githubusercontent.com/103496889/288259647-ce0ced30-6277-45b2-8ba7-ac19f258dc35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjk2NDAsIm5iZiI6MTcwMTgyOTM0MCwicGF0aCI6Ii8xMDM0OTY4ODkvMjg4MjU5NjQ3LWNlMGNlZDMwLTYyNzctNDViMi04YmE3LWFjMTlmMjU4ZGMzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjIyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTFjMjU1MGZkZmY2N2Y4YTJlOWNmNjMyMjBmMGFkOTgyMGZiM2E2MjRlYTZiOThiNmI5MjY1YjFlNzdhYjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kl9eZS8xdS5A8LOPHiRuOBQNQwMTN7ycpMK52RNhscs) ![image](https://private-user-images.githubusercontent.com/103496889/288259862-059c137d-a2eb-4396-a620-2ac45f040803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjk2NDAsIm5iZiI6MTcwMTgyOTM0MCwicGF0aCI6Ii8xMDM0OTY4ODkvMjg4MjU5ODYyLTA1OWMxMzdkLWEyZWItNDM5Ni1hNjIwLTJhYzQ1ZjA0MDgwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjIyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODMyMjg4MmU0YjQ5NDUxY2NkM2NjYTgwNGZmYWRjZDc4YjgzYzhmMzFjNmMxOGE3YzMwYjdjYWViZjYxODFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fR7NFbgfNr2tu4JBNVmBhLAffRrld_STYslrxbIkLkI)

😅 OK，复现了，看起来是滚动加载失效了，Working on it.

**Comment by gary-Shen** [comment]
请安装 刚刚发布的 `v0.8.2`，应该修复了 第二个问题；第一个数据ID跟上传文件数量没有直接关系，我想你想看的是序号吧？

**Comment by flinzhao** [comment]
![image](https://github.com/opendatalab/labelU/assets/103496889/a299efa3-aaeb-4d30-ac9a-12355faf5a19)
![image](https://github.com/opendatalab/labelU/assets/103496889/47c86ada-8d8c-4440-bfb9-d3d01f7724d9)
![image](https://github.com/opendatalab/labelU/assets/103496889/6cdcd44c-d60f-42c8-8fa6-079868d6e85c)
![image](https://github.com/opendatalab/labelU/assets/103496889/bb208d8e-e5be-4edb-97b9-4a47bca5f081)
通过pip install --upgrade已经更新到新版本了，但是图片列表还是只显示40张

**Comment by flinzhao** [comment]
> > ![image](https://private-user-images.githubusercontent.com/103496889/288259647-ce0ced30-6277-45b2-8ba7-ac19f258dc35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjk2NDAsIm5iZiI6MTcwMTgyOTM0MCwicGF0aCI6Ii8xMDM0OTY4ODkvMjg4MjU5NjQ3LWNlMGNlZDMwLTYyNzctNDViMi04YmE3LWFjMTlmMjU4ZGMzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjIyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTFjMjU1MGZkZmY2N2Y4YTJlOWNmNjMyMjBmMGFkOTgyMGZiM2E2MjRlYTZiOThiNmI5MjY1YjFlNzdhYjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kl9eZS8xdS5A8LOPHiRuOBQNQwMTN7ycpMK52RNhscs) ![image](https://private-user-images.githubusercontent.com/103496889/288259862-059c137d-a2eb-4396-a620-2ac45f040803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjk2NDAsIm5iZiI6MTcwMTgyOTM0MCwicGF0aCI6Ii8xMDM0OTY4ODkvMjg4MjU5ODYyLTA1OWMxMzdkLWEyZWItNDM5Ni1hNjIwLTJhYzQ1ZjA0MDgwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjIyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODMyMjg4MmU0YjQ5NDUxY2NkM2NjYTgwNGZmYWRjZDc4YjgzYzhmMzFjNmMxOGE3YzMwYjdjYWViZjYxODFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fR7NFbgfNr2tu4JBNVmBhLAffRrld_STYslrxbIkLkI)
> 
> 😅 OK，复现了，看起来是滚动加载失效了，Working on it.

![image](https://github.com/opendatalab/labelU/assets/103496889/2ccbc0a2-4b6d-4f7b-8a6d-ae117d6ff772)
图片加载不起来(^///^)

**Comment by flinzhao** [comment]
可以了👍👍👍
鼠标滚动后可以继续加载图像了😊
