### ISSUE TITLE
导出mask格式的多边形标注结果存在BUG

### ISSUE THREAD

**Issue by flinzhao** [opendatalab/labelU#69]
![image](https://github.com/opendatalab/labelU/assets/103496889/38015e6c-5240-4241-a8e1-78d1cbf1ccef)
导出mask格式的标注结果，以trainIds.png结尾的图像，掩码都是1吗？如果需要标注三类，掩码不应该对应1，2，3吗？

**Comment by gary-Shen** [comment]
> ![image](https://private-user-images.githubusercontent.com/103496889/288672980-38015e6c-5240-4241-a8e1-78d1cbf1ccef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5Mzc5MzYsIm5iZiI6MTcwMTkzNzYzNiwicGF0aCI6Ii8xMDM0OTY4ODkvMjg4NjcyOTgwLTM4MDE1ZTZjLTUyNDAtNDI0MS1hOGUxLTc4ZDFjYmYxY2NlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QwODI3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTgwMjg5MzQzYTA4NTQzNDY5NmM4NTUwNmQ2MDU4Y2U0MzU1YzRhMWViMjkxNDllYjQ3MGJkNDhiNDlkMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WdceWsDYEMyLEzB0AVJHAXA6MZxQtnPQenXx8p9LVKM) 导出mask格式的标注结果，以trainIds.png结尾的图像，掩码都是1吗？如果需要标注三类，掩码不应该对应1，2，3吗？

这里的 `fill=1`，跟类别没有关系吧？能详细讲讲你的需求吗？

**Comment by flinzhao** [comment]
如果需要模型分割people、cat、dog三种类别，对于people来说，应该是fill=1,对于cat来说，fill=2,对于dog来说，fill=3,这样才合理吧😬

**Comment by flinzhao** [comment]
如果不管对于什么类别，fill始终为1，那么生成的掩码只能做二类别分割任务

**Comment by gary-Shen** [comment]
明白了。现在多边形 mask 确实是将多分类的前景合到了一张图上，但是是不同颜色区分的。而 fill=1 表示的是所有分类的背景色。你是希望不同类别导出单独的前景图片吗？

**Comment by flinzhao** [comment]
![image](https://github.com/opendatalab/labelU/assets/103496889/7ea7cb88-1413-46f4-963c-e1fe41c5ec7e)
使用使用coco格式导出的json文件中的category_id字段为啥全是-1🤨

**Comment by gary-Shen** [comment]
> ![image](https://github.com/opendatalab/labelU/assets/103496889/7ea7cb88-1413-46f4-963c-e1fe41c5ec7e)
> 
> 使用使用coco格式导出的json文件中的category_id字段为啥全是-1🤨

Working on it.
