### ISSUE TITLE
【BUG】贴近边缘的标注失效

### ISSUE THREAD

**Issue by Gypsophila123** [opendatalab/labelU#97]
检查数据的时候发现有些标注的annotation["bbox"]=[]
![image](https://github.com/opendatalab/labelU/assets/63332682/0f385096-8f40-450f-9060-1aa6e9edfdce)
进入应用检查确认全部标注了
![image](https://github.com/opendatalab/labelU/assets/63332682/85b63582-c23b-44dc-8a1d-bc5a5bd4fbf8)
查看了几个annotation["bbox"]=[]的标注，发现都是标注框在边缘的情况
![image](https://github.com/opendatalab/labelU/assets/63332682/a65cceae-4fe5-4e5c-b69a-469f5c8af60e)

**Comment by gary-Shen** [comment]
谢谢反馈，我们试试复现一下。

**Comment by Gypsophila123** [comment]
再反馈一个问题，图片如果超过40张，前端可能会在第四十页显示完成而不是下一页，可能是因为一次只加载了40张图片
![image](https://github.com/opendatalab/labelU/assets/63332682/4c04446e-9ef0-4eb1-8bbd-8c771460f758)
