### ISSUE TITLE
开始新的标注任务，视频索引没有重置

### ISSUE THREAD

**Issue by Li-Lai** [opendatalab/labelU#98]
如题：索引累加，导致不清楚目前实际标注的索引是多少。数据ID如何才能重置呢？
![image](https://github.com/opendatalab/labelU/assets/12853603/ca31fc4a-fecd-4ede-afc6-6283144d7d5d)

**Comment by gary-Shen** [comment]
ID是不会重置的，你想要显示 1, 2, ...这样的索引是吗？

**Comment by gary-Shen** [comment]
升级一下版本再试试看。
