### ISSUE TITLE
视频分割标注bugs

### ISSUE THREAD

**Issue by Li-Lai** [opendatalab/labelU#99]
1：拖动打标的分割片段，分割片段的时长偶尔会出现负数
2：切换分割片段的标签后，跳到下一个视频偶尔会出现随机的分割标注片段
3：切换视频时，偶尔会将刚才上个标注的分割标注片段时间给改写。

**Comment by gary-Shen** [comment]
你通过鼠标进行标注的是吗？然后你使用的是在线体验版本还是本地版本？

**Comment by Li-Lai** [comment]
分割视频：使用X，拖动诗篇片段标注使用鼠标。本地版本。因为是偶发的，我这边后面看看能不能录制屏幕。

**Comment by Li-Lai** [comment]
全部复现了。。。视频大小超过限制了，我放到百度云吧
链接: https://pan.baidu.com/s/1-4FQi2KaZLCMkH1Wr_VvGQ?pwd=qxjf 
提取码: qxjf

**Comment by gary-Shen** [comment]
> 全部复现了。。。视频大小超过限制了，我放到百度云吧 链接: https://pan.baidu.com/s/1-4FQi2KaZLCMkH1Wr_VvGQ?pwd=qxjf 提取码: qxjf 视频：31s-50s：对应上面的bug3 视频：55s-1:26s：对应上面的bug2 视频：1:30s-2:20s：对应上面的bug1

OK。我们看看。

**Comment by gary-Shen** [comment]
> 1：拖动打标的分割片段，分割片段的时长偶尔会出现负数 2：切换分割片段的标签后，跳到下一个视频偶尔会出现随机的分割标注片段 3：切换视频时，偶尔会将刚才上个标注的分割标注片段时间给改写。

2、3 两个问题你升级一下版本再试试看？

**Comment by Li-Lai** [comment]
@gary-Shen 
升级到1.0.3后，简单测试了一下。问题2依旧存在，问题3有待观察。

**Comment by Li-Lai** [comment]
https://github.com/opendatalab/labelU/assets/12853603/60fa9cf7-7525-4685-8c28-ddbba4056d98

**Comment by Li-Lai** [comment]
@gary-Shen 1.0.4出现新bug啦，索引顺序错乱了。问题2，3貌似没有复现，明天我再多测试几次。

**Comment by gary-Shen** [comment]
> @gary-Shen 1.0.4出现新bug啦，索引顺序错乱了。问题2，3貌似没有复现，明天我再多测试几次。

这个顺序是我们内部提的 feature😂，文件按上传时间倒序。

**Comment by gary-Shen** [comment]
> @gary-Shen 1.0.4出现新bug啦，索引顺序错乱了。问题2，3貌似没有复现，明天我再多测试几次。

谢谢反馈。顺序的那个我们再评估一下要不要保留😀。

**Comment by Li-Lai** [comment]
> > @gary-Shen 1.0.4出现新bug啦，索引顺序错乱了。问题2，3貌似没有复现，明天我再多测试几次。
> 
> 谢谢反馈。顺序的那个我们再评估一下要不要保留😀。

新feature会导致一个问题：增加用户的步骤。在不选择的情况下，默认是列表的最后一个，标注好就是完成了，而不是跳到下一个。
